.github/workflows/cron.yaml, cron.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/2)
=> deploy cron jobs

cron.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/3)
=> Update cron job times and uncomment dev job

cron.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/4)
=> Enable final cron jobs

.github/workflows/dispatch.yaml, dispatch.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/19)
=> update routing rules

.github/workflows/dispatch.yaml, dispatch.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/20)
=> Fix dispatch 2

CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/23)
=> SKOcadoContributor

CONTRIBUTING.md, LICENSE.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/22)
=> contributing

codeforlife.code-workspace, docs/python/docstring.mustache
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/28)
=> python docstring template

CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/35)
=> Adding my contribution email

.github/workflows/verify-new-contributor.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/59)
=> type: number

.github/workflows/verify-new-contributor.yaml, .github/workflows/view-pull-request.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/60)
=> type: string

.github/workflows/validate-new-contributor.yaml, .github/workflows/verify-new-contributor.yaml, .github/workflows/view-pull-request.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/61)
=> Fix contrib 2

.github/workflows/validate-existing-contributors.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/64)
=> add pull request

.github/workflows/validate-pull-request-refs.yaml
validates that we are merging:
1. from dev into staging
2. from staging into production
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/67)
=> validate pr refs

.devcontainer/codeforlife-portal-react/devcontainer.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/72)
=> call setup.sh

.devcontainer/codeforlife-package-python/devcontainer.json, .devcontainer/codeforlife-portal-react/devcontainer.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/73)
=> add settings

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/75)
=> Add licence info to readme

.submodules/configs.jsonc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/79)
=> add tamasfe.even-better-toml extension to base

CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/80)
=> eve.martin@ocado.com

.github/workflows/test-python-code.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/99)
=> fix: pylint call

.github/actions/python/docs/action.yaml, .github/actions/python/setup-environment/action.yaml, .github/workflows/test-python-code.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/100)
=> Polish mypy

.github/workflows/test-python-code.yaml, .submodules/configs.jsonc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/102)
=> Polish test

.submodules/recurse-fork/__main__.py, .submodules/recurse-fork/run
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/107)
=> allow skipping login

CONTRIBUTING.md
Added my email address to contributors
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/109)
=> jibran19983@gmail.com

.github/scripts/python/validate-existing-contributors/__main__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/110)
=> Make contributor email check case insensitive

.github/scripts/python/validate-existing-contributors/__main__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/111)
=> add cfl bot

cron.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/120)
=> Remove unused cron, uncomment needed reminder crons for prod

CONTRIBUTING.md
Added my email address  to CONTRIBUTING.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/156)
=> gaganrh717@gmail.com

CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/159)
=> add email to the contribution.md

scripts/backend/run
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/160)
=> dynamic service port

CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/150)
=> user.email

.submodules/setup/__main__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/200)
=> fix: install snyk globally in dev container

.devcontainer/devcontainer.json, .github/actions/workspace/download-script-file/action.yaml, .github/workflows/frontend.yaml, .github/workflows/test-javascript-code.yaml, codeforlife.code-workspace, scripts/frontend/cli
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/207)
=> Portal frontend 48

.devcontainer/Dockerfile, .gitmodules, .submodules/setup/__main__.py, codeforlife.code-workspace
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/215)
=> fix dev container

.github/workflows/test-javascript-code.yaml, .github/workflows/test-python-code.yaml, scripts/backend/cli, scripts/frontend/cli
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/216)
=> Backend cli

.devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, .gitignore, .submodules/setup/run, codeforlife.code-workspace
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/217)
=> Workspace 194

.devcontainer/devcontainer.json, .github/actions/javascript/setup-environment/action.yaml, .github/workflows/frontend.yaml, .github/workflows/test-javascript-code.yaml, scripts/frontend/setup
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/223)
=> fix: Upgrade Node to 22

configs/frontend/.snyk
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/228)
=> Snyk ignore until mui upgrade
